// Extended content library with themed practice packs

export const ARABIC_THEMED_PACKS = {
  animals: [
    { word: 'قِطّ', transliteration: 'qiṭṭ', meaning: 'cat' },
    { word: 'كَلْب', transliteration: 'kalb', meaning: 'dog' },
    { word: 'عُصْفُور', transliteration: 'ʿuṣfūr', meaning: 'bird' },
    { word: 'سَمَكَة', transliteration: 'samaka', meaning: 'fish' },
    { word: 'فَأْر', transliteration: 'faʾr', meaning: 'mouse' },
    { word: 'أَرْنَب', transliteration: 'arnab', meaning: 'rabbit' },
    { word: 'حِصَان', transliteration: 'ḥiṣān', meaning: 'horse' },
    { word: 'بَقَرَة', transliteration: 'baqara', meaning: 'cow' },
    { word: 'خَرُوف', transliteration: 'kharūf', meaning: 'sheep' },
    { word: 'دَجَاجَة', transliteration: 'dajāja', meaning: 'chicken' },
    { word: 'بَطَّة', transliteration: 'baṭṭa', meaning: 'duck' },
    { word: 'فَرَاشَة', transliteration: 'farāsha', meaning: 'butterfly' },
    { word: 'نَحْلَة', transliteration: 'naḥla', meaning: 'bee' },
    { word: 'أَسَد', transliteration: 'asad', meaning: 'lion' },
    { word: 'فِيل', transliteration: 'fīl', meaning: 'elephant' },
    { word: 'زَرَافَة', transliteration: 'zarāfa', meaning: 'giraffe' },
    { word: 'قِرْد', transliteration: 'qird', meaning: 'monkey' },
    { word: 'دُب', transliteration: 'dubb', meaning: 'bear' },
    { word: 'ثَعْلَب', transliteration: 'thaʿlab', meaning: 'fox' },
    { word: 'ذِئْب', transliteration: 'dhiʾb', meaning: 'wolf' },
  ],
  
  food: [
    { word: 'تُفَّاحَة', transliteration: 'tuffāḥa', meaning: 'apple' },
    { word: 'مَوْز', transliteration: 'mawz', meaning: 'banana' },
    { word: 'بُرْتُقَال', transliteration: 'burtuqāl', meaning: 'orange' },
    { word: 'عِنَب', transliteration: 'ʿinab', meaning: 'grapes' },
    { word: 'فَرَاوْلَة', transliteration: 'farāwla', meaning: 'strawberry' },
    { word: 'خُبْز', transliteration: 'khubz', meaning: 'bread' },
    { word: 'حَلِيب', transliteration: 'ḥalīb', meaning: 'milk' },
    { word: 'جُبْن', transliteration: 'jubn', meaning: 'cheese' },
    { word: 'زُبْدَة', transliteration: 'zubda', meaning: 'butter' },
    { word: 'بَيْض', transliteration: 'bayḍ', meaning: 'eggs' },
    { word: 'أَرُزّ', transliteration: 'aruzz', meaning: 'rice' },
    { word: 'دَجَاج', transliteration: 'dajāj', meaning: 'chicken (meat)' },
    { word: 'لَحْم', transliteration: 'laḥm', meaning: 'meat' },
    { word: 'سَمَك', transliteration: 'samak', meaning: 'fish (food)' },
    { word: 'خُضَار', transliteration: 'khuḍār', meaning: 'vegetables' },
    { word: 'جَزَر', transliteration: 'jazar', meaning: 'carrots' },
    { word: 'طَمَاطِم', transliteration: 'ṭamāṭim', meaning: 'tomatoes' },
    { word: 'خِيَار', transliteration: 'khiyār', meaning: 'cucumber' },
    { word: 'بَطَاطِس', transliteration: 'baṭāṭis', meaning: 'potatoes' },
    { word: 'بَصَل', transliteration: 'baṣal', meaning: 'onion' },
  ],
  
  colors: [
    { word: 'أَحْمَر', transliteration: 'aḥmar', meaning: 'red' },
    { word: 'أَزْرَق', transliteration: 'azraq', meaning: 'blue' },
    { word: 'أَخْضَر', transliteration: 'akhḍar', meaning: 'green' },
    { word: 'أَصْفَر', transliteration: 'aṣfar', meaning: 'yellow' },
    { word: 'بُرْتُقَالِي', transliteration: 'burtuqālī', meaning: 'orange' },
    { word: 'بَنَفْسَجِي', transliteration: 'banafsajī', meaning: 'purple' },
    { word: 'وَرْدِي', transliteration: 'wardī', meaning: 'pink' },
    { word: 'بُنِّي', transliteration: 'bunnī', meaning: 'brown' },
    { word: 'أَبْيَض', transliteration: 'abyaḍ', meaning: 'white' },
    { word: 'أَسْوَد', transliteration: 'aswad', meaning: 'black' },
    { word: 'رَمَادِي', transliteration: 'ramādī', meaning: 'gray' },
  ],
  
  emotions: [
    { word: 'سَعِيد', transliteration: 'saʿīd', meaning: 'happy' },
    { word: 'حَزِين', transliteration: 'ḥazīn', meaning: 'sad' },
    { word: 'غَاضِب', transliteration: 'ghāḍib', meaning: 'angry' },
    { word: 'خَائِف', transliteration: 'khāʾif', meaning: 'scared' },
    { word: 'مُتَفَاجِئ', transliteration: 'mutafājiʾ', meaning: 'surprised' },
    { word: 'مُتَعَب', transliteration: 'mutaʿab', meaning: 'tired' },
    { word: 'نَشِيط', transliteration: 'nashīṭ', meaning: 'energetic' },
    { word: 'مُبْتَسِم', transliteration: 'mubtasim', meaning: 'smiling' },
    { word: 'هَادِئ', transliteration: 'hādiʾ', meaning: 'calm' },
    { word: 'مُنْزَعِج', transliteration: 'munzaʿij', meaning: 'upset' },
    { word: 'مُتَحَمِّس', transliteration: 'mutaḥammis', meaning: 'excited' },
  ],
  
  actions: [
    { word: 'يَجْرِي', transliteration: 'yajrī', meaning: 'runs' },
    { word: 'يَمْشِي', transliteration: 'yamshī', meaning: 'walks' },
    { word: 'يَقْفِز', transliteration: 'yaqfiz', meaning: 'jumps' },
    { word: 'يَلْعَب', transliteration: 'yalʿab', meaning: 'plays' },
    { word: 'يَأْكُل', transliteration: 'yaʾkul', meaning: 'eats' },
    { word: 'يَشْرَب', transliteration: 'yashrab', meaning: 'drinks' },
    { word: 'يَنَام', transliteration: 'yanām', meaning: 'sleeps' },
    { word: 'يَسْتَيْقِظ', transliteration: 'yastayqiẓ', meaning: 'wakes up' },
    { word: 'يَقْرَأ', transliteration: 'yaqraʾ', meaning: 'reads' },
    { word: 'يَكْتُب', transliteration: 'yaktub', meaning: 'writes' },
    { word: 'يَرْسُم', transliteration: 'yarsum', meaning: 'draws' },
    { word: 'يُغَنِّي', transliteration: 'yughannī', meaning: 'sings' },
    { word: 'يَرْقُص', transliteration: 'yarquṣ', meaning: 'dances' },
    { word: 'يَسْتَمِع', transliteration: 'yastamiʿ', meaning: 'listens' },
    { word: 'يَتَكَلَّم', transliteration: 'yatakallam', meaning: 'speaks' },
  ],
  
  family: [
    { word: 'أَب', transliteration: 'ab', meaning: 'father' },
    { word: 'أُم', transliteration: 'umm', meaning: 'mother' },
    { word: 'أَخ', transliteration: 'akh', meaning: 'brother' },
    { word: 'أُخْت', transliteration: 'ukht', meaning: 'sister' },
    { word: 'جَد', transliteration: 'jadd', meaning: 'grandfather' },
    { word: 'جَدَّة', transliteration: 'jadda', meaning: 'grandmother' },
    { word: 'عَم', transliteration: 'ʿamm', meaning: 'paternal uncle' },
    { word: 'عَمَّة', transliteration: 'ʿamma', meaning: 'paternal aunt' },
    { word: 'خَال', transliteration: 'khāl', meaning: 'maternal uncle' },
    { word: 'خَالَة', transliteration: 'khāla', meaning: 'maternal aunt' },
    { word: 'اِبْن', transliteration: 'ibn', meaning: 'son' },
    { word: 'بِنْت', transliteration: 'bint', meaning: 'daughter' },
  ],
  
  body: [
    { word: 'رَأْس', transliteration: 'raʾs', meaning: 'head' },
    { word: 'عَيْن', transliteration: 'ʿayn', meaning: 'eye' },
    { word: 'أُذُن', transliteration: 'udhun', meaning: 'ear' },
    { word: 'أَنْف', transliteration: 'anf', meaning: 'nose' },
    { word: 'فَم', transliteration: 'fam', meaning: 'mouth' },
    { word: 'أَسْنَان', transliteration: 'asnān', meaning: 'teeth' },
    { word: 'لِسَان', transliteration: 'lisān', meaning: 'tongue' },
    { word: 'يَد', transliteration: 'yad', meaning: 'hand' },
    { word: 'إِصْبَع', transliteration: 'iṣbaʿ', meaning: 'finger' },
    { word: 'رِجْل', transliteration: 'rijl', meaning: 'leg/foot' },
    { word: 'قَدَم', transliteration: 'qadam', meaning: 'foot' },
    { word: 'رُكْبَة', transliteration: 'rukba', meaning: 'knee' },
    { word: 'ذِرَاع', transliteration: 'dhirāʿ', meaning: 'arm' },
    { word: 'كَتِف', transliteration: 'katif', meaning: 'shoulder' },
    { word: 'بَطْن', transliteration: 'baṭn', meaning: 'stomach' },
  ],
}

export const ENGLISH_THEMED_PACKS = {
  animals: [
    { word: 'cat', phonetic: 'kæt' },
    { word: 'dog', phonetic: 'dɒg' },
    { word: 'bird', phonetic: 'bɜrd' },
    { word: 'fish', phonetic: 'fɪʃ' },
    { word: 'mouse', phonetic: 'maʊs' },
    { word: 'rabbit', phonetic: 'ræbɪt' },
    { word: 'horse', phonetic: 'hɔrs' },
    { word: 'cow', phonetic: 'kaʊ' },
    { word: 'sheep', phonetic: 'ʃip' },
    { word: 'chicken', phonetic: 'tʃɪkən' },
    { word: 'duck', phonetic: 'dʌk' },
    { word: 'butterfly', phonetic: 'bʌtərflaɪ' },
    { word: 'bee', phonetic: 'bi' },
    { word: 'lion', phonetic: 'laɪən' },
    { word: 'elephant', phonetic: 'ɛləfənt' },
    { word: 'giraffe', phonetic: 'dʒəræf' },
    { word: 'monkey', phonetic: 'mʌŋki' },
    { word: 'bear', phonetic: 'bɛr' },
    { word: 'fox', phonetic: 'fɒks' },
    { word: 'wolf', phonetic: 'wʊlf' },
  ],
  
  food: [
    { word: 'apple', phonetic: 'æpəl' },
    { word: 'banana', phonetic: 'bənænə' },
    { word: 'orange', phonetic: 'ɔrɪndʒ' },
    { word: 'grapes', phonetic: 'greɪps' },
    { word: 'strawberry', phonetic: 'strɔbɛri' },
    { word: 'bread', phonetic: 'brɛd' },
    { word: 'milk', phonetic: 'mɪlk' },
    { word: 'cheese', phonetic: 'tʃiz' },
    { word: 'butter', phonetic: 'bʌtər' },
    { word: 'eggs', phonetic: 'ɛgz' },
    { word: 'rice', phonetic: 'raɪs' },
    { word: 'chicken', phonetic: 'tʃɪkən' },
    { word: 'meat', phonetic: 'mit' },
    { word: 'fish', phonetic: 'fɪʃ' },
    { word: 'vegetables', phonetic: 'vɛdʒtəbəlz' },
    { word: 'carrots', phonetic: 'kærəts' },
    { word: 'tomatoes', phonetic: 'təmeɪtoʊz' },
    { word: 'cucumber', phonetic: 'kjukʌmbər' },
    { word: 'potatoes', phonetic: 'pəteɪtoʊz' },
    { word: 'onion', phonetic: 'ʌnjən' },
  ],
  
  colors: [
    { word: 'red', phonetic: 'rɛd' },
    { word: 'blue', phonetic: 'blu' },
    { word: 'green', phonetic: 'grin' },
    { word: 'yellow', phonetic: 'jɛloʊ' },
    { word: 'orange', phonetic: 'ɔrɪndʒ' },
    { word: 'purple', phonetic: 'pɜrpəl' },
    { word: 'pink', phonetic: 'pɪŋk' },
    { word: 'brown', phonetic: 'braʊn' },
    { word: 'white', phonetic: 'waɪt' },
    { word: 'black', phonetic: 'blæk' },
    { word: 'gray', phonetic: 'greɪ' },
  ],
  
  emotions: [
    { word: 'happy', phonetic: 'hæpi' },
    { word: 'sad', phonetic: 'sæd' },
    { word: 'angry', phonetic: 'æŋgri' },
    { word: 'scared', phonetic: 'skɛrd' },
    { word: 'surprised', phonetic: 'sərpraɪzd' },
    { word: 'tired', phonetic: 'taɪərd' },
    { word: 'excited', phonetic: 'ɪksaɪtɪd' },
    { word: 'calm', phonetic: 'kɑm' },
    { word: 'upset', phonetic: 'ʌpsɛt' },
    { word: 'worried', phonetic: 'wɜrid' },
  ],
  
  actions: [
    { word: 'run', phonetic: 'rʌn' },
    { word: 'walk', phonetic: 'wɔk' },
    { word: 'jump', phonetic: 'dʒʌmp' },
    { word: 'play', phonetic: 'pleɪ' },
    { word: 'eat', phonetic: 'it' },
    { word: 'drink', phonetic: 'drɪŋk' },
    { word: 'sleep', phonetic: 'slip' },
    { word: 'wake', phonetic: 'weɪk' },
    { word: 'read', phonetic: 'rid' },
    { word: 'write', phonetic: 'raɪt' },
    { word: 'draw', phonetic: 'drɔ' },
    { word: 'sing', phonetic: 'sɪŋ' },
    { word: 'dance', phonetic: 'dæns' },
    { word: 'listen', phonetic: 'lɪsən' },
    { word: 'speak', phonetic: 'spik' },
  ],
  
  family: [
    { word: 'father', phonetic: 'fɑðər' },
    { word: 'mother', phonetic: 'mʌðər' },
    { word: 'brother', phonetic: 'brʌðər' },
    { word: 'sister', phonetic: 'sɪstər' },
    { word: 'grandfather', phonetic: 'grændfɑðər' },
    { word: 'grandmother', phonetic: 'grændmʌðər' },
    { word: 'uncle', phonetic: 'ʌŋkəl' },
    { word: 'aunt', phonetic: 'ænt' },
    { word: 'son', phonetic: 'sʌn' },
    { word: 'daughter', phonetic: 'dɔtər' },
  ],
  
  body: [
    { word: 'head', phonetic: 'hɛd' },
    { word: 'eye', phonetic: 'aɪ' },
    { word: 'ear', phonetic: 'ɪr' },
    { word: 'nose', phonetic: 'noʊz' },
    { word: 'mouth', phonetic: 'maʊθ' },
    { word: 'teeth', phonetic: 'tiθ' },
    { word: 'tongue', phonetic: 'tʌŋ' },
    { word: 'hand', phonetic: 'hænd' },
    { word: 'finger', phonetic: 'fɪŋgər' },
    { word: 'leg', phonetic: 'lɛg' },
    { word: 'foot', phonetic: 'fʊt' },
    { word: 'knee', phonetic: 'ni' },
    { word: 'arm', phonetic: 'ɑrm' },
    { word: 'shoulder', phonetic: 'ʃoʊldər' },
    { word: 'stomach', phonetic: 'stʌmək' },
  ],
}

// Get themed pack by category and language
export function getThemedPack(language: 'arabic' | 'english', category: string) {
  if (language === 'arabic') {
    return ARABIC_THEMED_PACKS[category as keyof typeof ARABIC_THEMED_PACKS] || []
  }
  return ENGLISH_THEMED_PACKS[category as keyof typeof ENGLISH_THEMED_PACKS] || []
}

// Get all available categories
export function getAvailableCategories(language: 'arabic' | 'english') {
  if (language === 'arabic') {
    return Object.keys(ARABIC_THEMED_PACKS)
  }
  return Object.keys(ENGLISH_THEMED_PACKS)
}
